window.KOSHRA_DATA = {
  products: [
    {id:"classic",slug:"the-classic-appreciation-box",name:"The Classic Appreciation Box",category:"Gift Boxes",price:1295,corporate:1080,description:"Roasted almonds, whole cashews, pistachios and premium dates in a forest-green rigid box.",contents:"Almonds · Cashews · Pistachios · Dates",weight:"600 g",compartments:4,material:"FSC-certified rigid board",shelf:"4 months",allergens:"Contains tree nuts",personalise:true,moq:25,dispatch:"2–3 business days",tags:["bestseller","corporate","diwali"],stock:"In stock",image:"assets/koshra-hero.jpg",crop:"right"},
    {id:"executive",slug:"the-executive-reserve",name:"The Executive Reserve",category:"Executive",price:2495,corporate:2180,description:"Six considered ingredients in a reusable presentation box designed for leadership and client gifting.",contents:"Mamra almonds · Cashews · Pistachios · Walnuts · Medjoul dates · Berries",weight:"900 g",compartments:6,material:"Textured rigid board",shelf:"4 months",allergens:"Contains tree nuts",personalise:true,moq:20,dispatch:"3–4 business days",tags:["premium","corporate","bestseller"],stock:"Low stock",image:"assets/koshra-corporate-desk.jpg",crop:"center"},
    {id:"pistachio",slug:"the-pistachio-edit",name:"The Pistachio Edit",category:"Dry Fruits",price:1495,corporate:1260,description:"A focused selection of roasted, salted and natural pistachios for the enthusiast.",contents:"Natural · Lightly salted · Roasted pistachios",weight:"450 g",compartments:3,material:"Forest rigid board",shelf:"4 months",allergens:"Contains pistachios",personalise:true,moq:30,dispatch:"2–3 business days",tags:["dry-fruits","client-gifting"],stock:"In stock",image:"assets/koshra-unboxing.jpg",crop:"bottom"},
    {id:"wellness",slug:"the-wellness-collection",name:"The Wellness Collection",category:"Wellness",price:1695,corporate:1450,description:"Nuts, seeds, dried berries and an everyday trail mix with no added confectionery.",contents:"Almonds · Walnuts · Seeds · Berries · Trail mix",weight:"700 g",compartments:5,material:"Recycled kraft rigid box",shelf:"3 months",allergens:"Contains tree nuts and seeds",personalise:true,moq:25,dispatch:"2–3 business days",tags:["wellness","vegan","corporate"],stock:"In stock",image:"assets/dried-fruits-unsplash.jpg",crop:"center"},
    {id:"festive",slug:"the-festive-quartet",name:"The Festive Quartet",category:"Festive",price:1895,corporate:1580,description:"Four generous dry-fruit selections with a burgundy ribbon and festival message card.",contents:"Almonds · Cashews · Pistachios · Dates",weight:"720 g",compartments:4,material:"Rigid board with paper sleeve",shelf:"4 months",allergens:"Contains tree nuts",personalise:true,moq:25,dispatch:"3–4 business days",tags:["diwali","festive","bestseller"],stock:"In stock",image:"assets/gift-ribbon-pexels.jpg",crop:"center"},
    {id:"wooden",slug:"the-signature-wooden-chest",name:"The Signature Wooden Chest",category:"Executive",price:4495,corporate:3990,description:"A six-compartment mango-wood box with engraving and a removable food-safe inner tray.",contents:"Mamra almonds · Cashews · Pistachios · Walnuts · Dates · Berries",weight:"1.1 kg",compartments:6,material:"Mango wood and food-safe trays",shelf:"4 months",allergens:"Contains tree nuts",personalise:true,moq:15,dispatch:"5–7 business days",tags:["premium","engraving","leadership"],stock:"Made to order",image:"assets/koshra-corporate-desk.jpg",crop:"left"},
    {id:"gratitude",slug:"the-everyday-gratitude-box",name:"The Everyday Gratitude Box",category:"Gift Boxes",price:895,corporate:760,description:"A compact two-part gift for simple thank-yous, joining kits and event speakers.",contents:"Roasted almonds · Whole cashews",weight:"300 g",compartments:2,material:"Kraft drawer box",shelf:"4 months",allergens:"Contains tree nuts",personalise:true,moq:40,dispatch:"1–2 business days",tags:["under-1000","employee","ready"],stock:"Ready to dispatch",image:"assets/gift-wrapping-pexels.jpg",crop:"center"},
    {id:"client",slug:"the-client-thank-you-collection",name:"The Client Thank-You Collection",category:"Corporate",price:2195,corporate:1840,description:"A restrained client gift with four dry fruits, dark chocolate and a logo-ready sleeve.",contents:"Almonds · Cashews · Pistachios · Dates · Dark chocolate",weight:"800 g",compartments:5,material:"Rigid board and removable sleeve",shelf:"3 months",allergens:"Contains tree nuts, milk and soy",personalise:true,moq:25,dispatch:"4–5 business days",tags:["corporate","client-gifting","branding"],stock:"In stock",image:"assets/koshra-dispatch.jpg",crop:"center"},
    {id:"dates",slug:"the-royal-date-selection",name:"The Royal Date Selection",category:"Dates",price:1795,corporate:1510,description:"Medjoul, Ajwa and filled dates arranged in a slim executive presentation box.",contents:"Medjoul · Ajwa · Almond-filled dates",weight:"600 g",compartments:3,material:"Textured rigid board",shelf:"2 months",allergens:"Filled variety contains almonds",personalise:true,moq:25,dispatch:"2–3 business days",tags:["dates","executive","ramadan"],stock:"In stock",image:"assets/koshra-hero.jpg",crop:"bottom"},
    {id:"mindful",slug:"the-mindful-snacking-box",name:"The Mindful Snacking Box",category:"Wellness",price:1195,corporate:990,description:"Portion-ready nuts, seeds and fruit for desks, offsites and employee programmes.",contents:"Trail mix · Pumpkin seeds · Almonds · Berries",weight:"480 g",compartments:4,material:"Recycled board",shelf:"3 months",allergens:"Contains tree nuts and seeds",personalise:true,moq:50,dispatch:"3–4 business days",tags:["wellness","employee","vegan"],stock:"In stock",image:"assets/dried-fruits-unsplash.jpg",crop:"left"},
    {id:"trunk",slug:"the-celebration-trunk",name:"The Celebration Trunk",category:"Festive",price:5295,corporate:4650,description:"A generous eight-part gift with dry fruits, dates and small-batch snacks for milestone occasions.",contents:"Eight dry-fruit and snack selections",weight:"1.6 kg",compartments:8,material:"Fabric-finish trunk",shelf:"3 months",allergens:"Contains tree nuts, seeds, milk and soy",personalise:true,moq:10,dispatch:"5–7 business days",tags:["festive","wedding","premium"],stock:"Made to order",image:"assets/koshra-unboxing.jpg",crop:"center"},
    {id:"bespoke",slug:"the-bespoke-corporate-box",name:"The Bespoke Corporate Box",category:"Corporate",price:2995,corporate:2350,description:"A configurable six-part corporate gift with custom colours, contents and recipient messaging.",contents:"Configured to requirement",weight:"From 800 g",compartments:6,material:"Choice of rigid board, wood or kraft",shelf:"Confirmed after selection",allergens:"Depends on selected contents",personalise:true,moq:50,dispatch:"10–15 business days",tags:["corporate","custom","branding"],stock:"Quote required",image:"assets/koshra-dispatch.jpg",crop:"right"}
  ],
  collections: [
    {name:"Client appreciation",copy:"Restrained boxes with practical branding space.",image:"assets/koshra-corporate-desk.jpg",href:"collections.html?occasion=clients",tone:"forest"},
    {name:"Employee gifting",copy:"Thoughtful formats from onboarding to Diwali.",image:"assets/koshra-dispatch.jpg",href:"collections.html?occasion=employees",tone:"almond"},
    {name:"Executive selection",copy:"Presentation pieces for leadership and key partners.",image:"assets/koshra-hero.jpg",href:"collections.html?occasion=leadership",tone:"burgundy"},
    {name:"Wellness boxes",copy:"Ingredients first, with dietary details kept visible.",image:"assets/dried-fruits-unsplash.jpg",href:"collections.html?occasion=wellness",tone:"pistachio"},
    {name:"Festive gifting",copy:"A modern Indian festive language without excess.",image:"assets/koshra-unboxing.jpg",href:"collections.html?occasion=diwali",tone:"copper"},
    {name:"Build your own",copy:"Choose the box, contents, message and delivery.",image:"assets/gift-wrapping-pexels.jpg",href:"build-your-box.html",tone:"ivory"}
  ],
  ingredients: [
    {name:"Almonds",price:180,weight:"100 g",allergen:"Tree nut"},{name:"Cashews",price:210,weight:"100 g",allergen:"Tree nut"},{name:"Pistachios",price:260,weight:"100 g",allergen:"Tree nut"},{name:"Walnuts",price:230,weight:"100 g",allergen:"Tree nut"},{name:"Raisins",price:120,weight:"100 g",allergen:"None listed"},{name:"Medjoul dates",price:240,weight:"120 g",allergen:"None listed"},{name:"Dried berries",price:190,weight:"90 g",allergen:"Check final spec"},{name:"Seed mix",price:130,weight:"100 g",allergen:"Seeds"},{name:"Trail mix",price:160,weight:"100 g",allergen:"Tree nuts, seeds"},{name:"Dark chocolate",price:220,weight:"90 g",allergen:"Soy; may contain milk"}
  ]
};
