const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('#site-nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Open navigation':'Close navigation');nav.classList.toggle('is-open',!open)});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){menu.click();menu.focus()}});
nav?.querySelectorAll('a').forEach(a=>{if(a.pathname===location.pathname)a.setAttribute('aria-current','page')});

document.querySelectorAll('[data-concern]').forEach(link=>{const select=document.querySelector('#concern-select');if(select)link.addEventListener('click',()=>{select.value=link.dataset.concern});else{const destination=new URL(link.href);destination.searchParams.set('concern',link.dataset.concern);link.href=destination.href;}});
const preselectedConcern=new URLSearchParams(location.search).get('concern');const concernSelect=document.querySelector('#concern-select');if(concernSelect&&[...concernSelect.options].some(option=>option.value===preselectedConcern))concernSelect.value=preselectedConcern;
const filmDialog=document.querySelector('#film-dialog');const featureFilm=document.querySelector('#feature-film');
document.querySelector('#open-film')?.addEventListener('click',()=>{document.querySelector('#hero-video')?.pause();filmDialog.showModal();featureFilm.play().catch(()=>{})});
document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close()}});dialog.addEventListener('close',()=>{if(dialog===filmDialog)featureFilm.pause()})});
document.querySelector('#inspection-form')?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const list=document.querySelector('#request-summary');list.replaceChildren();[['name','Name'],['email','Email'],['area','Property area'],['concern','Reason'],['message','Details']].forEach(([key,label])=>{if(!data.get(key))return;const term=document.createElement('dt');term.textContent=label;const value=document.createElement('dd');value.textContent=data.get(key);list.append(term,value)});document.querySelector('#request-dialog').showModal()});
document.querySelector('#open-film-secondary')?.addEventListener('click',()=>document.querySelector('#open-film')?.click());
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});document.querySelectorAll('[data-category]').forEach(figure=>figure.hidden=button.dataset.filter!=='all'&&figure.dataset.category!==button.dataset.filter)}));
document.querySelectorAll('.gallery-open').forEach(button=>button.addEventListener('click',()=>{const img=document.querySelector('#lightbox-image');img.src=button.dataset.image;img.alt=button.dataset.caption;document.querySelector('#lightbox-caption').textContent=button.dataset.caption;document.querySelector('#image-dialog').showModal()}));
document.querySelectorAll('.micro-play').forEach(button=>{const label=button.getAttribute('aria-label').replace(/^Play /,'');const initialText=button.textContent;const video=button.parentElement.querySelector('video');const sync=()=>{button.textContent=video.paused?initialText:'Pause illustration';button.setAttribute('aria-label',`${video.paused?'Play':'Pause'} ${label}`)};button.addEventListener('click',()=>{if(!video.src)video.src=video.dataset.microVideo;if(video.paused){video.currentTime=0;video.play().catch(sync)}else video.pause()});video.addEventListener('play',sync);video.addEventListener('pause',sync);video.addEventListener('ended',sync);});
